# Generated by Django 6.0 on 2025-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_code', models.CharField(max_length=50)),
                ('client_address', models.TextField()),
                ('project_name', models.CharField(max_length=255)),
                ('warehouse', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
