"""
Django settings for StockHub project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for StockHub project (development friendly).

Notes:
- This configuration is suitable for local development only.
- BEFORE deploying to production:
  * set DEBUG = False
  * set a proper SECRET_KEY via environment variable
  * tighten ALLOWED_HOSTS
  * configure a production database & static/media serving
"""

import os
from pathlib import Path

# BASE_DIR: project's root (StockHub/)
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
# Use env var in production: export DJANGO_SECRET_KEY="..."
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-REPLACE_ME_FOR_PRODUCTION')

# Development convenience: set to False in prod.
DEBUG = True

# Local hosts for dev. Replace or restrict in production.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # your apps
    'accounts',
]

# If you created a custom user model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Helpful during development for serving static files with whitenoise if added
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StockHub.urls'

# Templates: top-level templates folder + app templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # create this folder for project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',   # useful in templates
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StockHub.wsgi.application'

# Database: default sqlite for local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validators (keep for production)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
# Set to your timezone; you mentioned Lagos earlier so this fits
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JS, images)
STATIC_URL = '/static/'
# Directory where collectstatic will copy files (used in production)
STATIC_ROOT = BASE_DIR / 'staticfiles'   # run collectstatic in production
# Additional locations for static files in development
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Development convenience: print some helpful info to console
if DEBUG:
    print("⚙️ Running in DEBUG mode. Remember to set DEBUG = False in production.")
    print("Static files served from:", STATICFILES_DIRS)
