# Generated by Django 6.0 on 2025-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('warehouse', models.CharField(max_length=100)),
                ('quantity_issued', models.PositiveIntegerField()),
                ('stock_balance', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
